### ISSUE TITLE
create_render_pipeline error

### ISSUE THREAD

**Issue by Achill113** [Neopallium/bevy_water#29]
Whenever water would be rendered I receive the error output below. I have tested having the `WaterPlugin` added, but no water to render and there is no errors.

I've also tested this on Windows 11 as well as Pop!_OS 22.04.

This is the simplest version of the code which causes the error.
```rust
use bevy::prelude::*;
use bevy_water::{WaterPlugin as BevyWaterPlugin, *};

pub struct WaterPlugin;

impl Plugin for WaterPlugin {
    fn build(&self, app: &mut App) {
        app
            .insert_resource(WaterSettings {
                spawn_tiles: Some(UVec2::new(10, 10)),
                ..default()
            })
            .add_plugins(BevyWaterPlugin);
    }
}
```

Error Output:
```
2024-03-23T23:01:51.863351Z  INFO bevy_winit::system: Creating new window "Play Koi" (0v1)
2024-03-23T23:01:51.863533Z  INFO log: Guessed window scale factor: 1    
2024-03-23T23:01:51.896667Z  INFO bevy_render::renderer: AdapterInfo { name: "AMD Radeon RX 7900 XTX (RADV NAVI31)", vendor: 4098, device: 29772, device_type: DiscreteGpu, driver: "radv", driver_info: "Mesa 24.0.0-1pop0~1706872735~22.04~0fa430c", backend: Vulkan }
2024-03-23T23:01:52.160780Z  INFO log: Gamepad /dev/input/event3 (ASRock LED Controller) connected.    
2024-03-23T23:01:52.177643Z  INFO bevy_input::gamepad: Gamepad { id: 0 } Connected
2024-03-23T23:01:52.177754Z  INFO play_koi::plugins::camera_controller: 
2024-03-23T23:01:52.248743Z ERROR log: Device::create_render_pipeline error: Error matching ShaderStages(VERTEX) shader requirements against the pipeline    
2024-03-23T23:01:52.248764Z ERROR log: Handling wgpu errors as fatal by default    
thread 'Async Compute Task Pool (3)' panicked at /home/achill113/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.19.3/src/backend/wgpu_core.rs:3006:5:
wgpu error: Validation Error

Caused by:
    In Device::create_render_pipeline
      note: label = `pbr_alpha_blend_mesh_pipeline`
    Error matching ShaderStages(VERTEX) shader requirements against the pipeline
    Shader global ResourceBinding { group: 0, binding: 9 } is not available in the pipeline layout
    Visibility flags don't include the shader stage


note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Encountered a panic in system `bevy_render::render_resource::pipeline_cache::PipelineCache::process_pipeline_queue_system`!
thread 'Compute Task Pool (1)' panicked at /home/achill113/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_render-0.13.0/src/pipelined_rendering.rs:49:67:
called `Result::unwrap()` on an `Err` value: RecvError
```

**Comment by Neopallium** [comment]
That error is caused by a bug in the `0.13.0` release of bevy.  You need to update `bevy` to `0.13.1`.

`cargo update -p bevy`

**Comment by Achill113** [comment]
> That error is caused by a bug in the `0.13.0` release of bevy.  You need to update `bevy` to `0.13.1`.
> 
> `cargo update -p bevy`

Thank you for the quick response 😊
