### ISSUE TITLE
Using this in Bevy Editor PLS I get a crash when opening the Assets window 

### ISSUE THREAD

**Issue by ethereumdegen** [Neopallium/bevy_water#30]
```
thread 'main' panicked at /home/andy/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_asset-0.13.1/src/reflect.rs:159:36:
Requested resource bevy_asset::assets::Assets<bevy_water::water::material::WaterMaterial> does not exist in the `World`.
                Did you forget to add it using `app.insert_resource` / `app.init_resource`?
                Resources are also implicitly added via `app.add_event`,
                and can be added by plugins.
stack backtrace:
   0: rust_begin_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
   2: bevy_ecs::world::World::resource
             at /home/andy/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.13.1/src/world/mod.rs:1295:21
   3: <bevy_asset::reflect::ReflectAsset as bevy_reflect::type_registry::FromType<A>>::from_type::{{closure}}
             at /home/andy/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_asset-0.13.1/src/reflect.rs:159:30
   4: core::ops::function::FnOnce::call_once

```

**Comment by Neopallium** [comment]
Should be fixed by: https://github.com/Neopallium/bevy_water/commit/8328db5198ec2f47873ce2912491ab37e42b3af8
Publishing version 0.13.1 now.
